CC=gcc
CXX=g++
CFLAGS=-Wall -O2
LDFLAGS=-lws2_32

TARGET_CLIENT=client
TARGET_SERVER=server

SRC_CLIENT=client.c
SRC_SERVER=server.cpp

all: $(TARGET_CLIENT) $(TARGET_SERVER)

$(TARGET_CLIENT): $(SRC_CLIENT)
	$(CC) $(CFLAGS) -o $(TARGET_CLIENT) $(SRC_CLIENT) $(LDFLAGS)

$(TARGET_SERVER): $(SRC_SERVER)
	$(CXX) $(CFLAGS) -o $(TARGET_SERVER) $(SRC_SERVER) $(LDFLAGS)

clean:
	rm -f $(TARGET_CLIENT).exe $(TARGET_SERVER).exe

