  - name: Install tools
    run: |
      sudo apt-get update
      sudo apt-get install -y doxygen graphviz universal-ctags python3

  - name: List repo (debug)
    run: |
      echo "===== tree (top) ====="
      ls -la
      echo "===== find C/C++ files ====="
      find . -type f \( -name "*.c" -o -name "*.cc" -o -name "*.cpp" -o -name "*.cxx" -o -name "*.h" -o -name "*.hpp" \) | sed 's/^/ - /'

  - name: Test ctags on common paths
    run: |
      which ctags || true
      ctags --version || true
      for f in server.cpp src/server.cpp ./server.cpp ./src/server.cpp; do
        if [ -f "$f" ]; then
          echo "---- ctags -x --c-kinds=f $f ----"
          ctags -x --c-kinds=f "$f" || true
        fi
      done

  - name: Build symbol map (auto-discover)
    env:
      SYMLINK_REPO: cnbissolution/sample_codes
      SYMLINK_BRANCH: main
    run: |
      python3 scripts/build_symbol_map_autodiscover.py
      echo "---- redirects_generated.json ----"
      test -f redirects_generated.json && cat redirects_generated.json || echo "(not generated)"

  - name: Generate redirect pages inside Doxygen site (lenient)
    run: |
      python3 scripts/generate_redirects_doxygen_site_lenient.py
      echo "---- list sym dir ----"
      if [ -d docs_build/html/sym ]; then find docs_build/html/sym -maxdepth 3 -type f -name index.html -print; else echo "(no sym dir)"; fi
